package forex;
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Subasri
 */
public class ViewAccount extends javax.swing.JFrame {

    /**
     * Creates new form ViewAccount of the user
     */

    public String UName; 
    
    ViewAccount(String UName) {
        this.UName  = UName;
        initComponents();
        displayRecord();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTitle = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        Luname = new javax.swing.JLabel();
        Lmailid = new javax.swing.JLabel();
        Lphno = new javax.swing.JLabel();
        Lrole = new javax.swing.JLabel();
        Drole = new javax.swing.JLabel();
        display = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Dname = new javax.swing.JTextField();
        Duname = new javax.swing.JTextField();
        Dmailid = new javax.swing.JTextField();
        Dphno = new javax.swing.JTextField();
        modify = new javax.swing.JButton();
        update = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LTitle.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        LTitle.setText("VIEW YOUR ACCOUNT");
        getContentPane().add(LTitle);
        LTitle.setBounds(307, 61, 478, 59);

        Lname.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Lname.setText("Name");
        getContentPane().add(Lname);
        Lname.setBounds(188, 187, 199, 57);

        Luname.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Luname.setText("User name");
        getContentPane().add(Luname);
        Luname.setBounds(190, 270, 199, 41);

        Lmailid.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Lmailid.setText("Email - id");
        getContentPane().add(Lmailid);
        Lmailid.setBounds(188, 341, 199, 40);

        Lphno.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Lphno.setText("Phone number");
        getContentPane().add(Lphno);
        Lphno.setBounds(188, 404, 199, 54);

        Lrole.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Lrole.setText("Role");
        getContentPane().add(Lrole);
        Lrole.setBounds(188, 476, 199, 42);

        Drole.setBackground(new java.awt.Color(255, 255, 255));
        Drole.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        Drole.setOpaque(true);
        getContentPane().add(Drole);
        Drole.setBounds(493, 476, 323, 42);

        display.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        display.setText("DISPLAY ITEMS");
        getContentPane().add(display);
        display.setBounds(100, 550, 231, 43);

        delete.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        delete.setText("DELETE ACCOUNT");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(380, 550, 257, 43);

        logout.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(940, 550, 145, 43);

        Dname.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Dname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DnameActionPerformed(evt);
            }
        });
        getContentPane().add(Dname);
        Dname.setBounds(490, 180, 330, 40);

        Duname.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        getContentPane().add(Duname);
        Duname.setBounds(493, 242, 323, 49);

        Dmailid.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Dmailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DmailidActionPerformed(evt);
            }
        });
        getContentPane().add(Dmailid);
        Dmailid.setBounds(493, 321, 323, 40);

        Dphno.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        getContentPane().add(Dphno);
        Dphno.setBounds(493, 394, 320, 44);

        modify.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        modify.setText("MODIFY DETAILS");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        getContentPane().add(modify);
        modify.setBounds(660, 550, 253, 43);

        update.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        update.setText("UPDATE DETAILS");
        update.setOpaque(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(870, 320, 251, 60);

        BG.setBackground(new java.awt.Color(255, 153, 255));
        BG.setOpaque(true);
        getContentPane().add(BG);
        BG.setBounds(-9, 0, 1190, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayRecord(){
        Dname.setEditable(false);
        Dphno.setEditable(false);
        Dmailid.setEditable(false);
        Duname.setEditable(false);
        update.setVisible(false);
         try{
            ResultSet rs;   
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/forex","root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "select * from accountDetails where userName='"+UName+"';";
            rs = stmt.executeQuery(query);
            if(rs.next()){
                    Duname.setText(rs.getString("userName"));
                    Dname.setText(rs.getString("name"));
                    Dphno.setText(rs.getString("phno"));
                    Dmailid.setText(rs.getString("email"));
                    if(rs.getString("role").equals("b"))
                        Drole.setText("buyer");
                    else
                        Drole.setText("seller");
                }
                else
                    JOptionPane.showMessageDialog(null, "Please enter a valid username and password", "Error message",1);
               
            }
            
         
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        update.setVisible(false);
        new Logout().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void DnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DnameActionPerformed

    private void DmailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DmailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DmailidActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
 
        Duname.setEditable(true);
        Dphno.setEditable(true);
        Dmailid.setEditable(true);
        update.setVisible(true);
    }//GEN-LAST:event_modifyActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        Duname.setEditable(false);
        Dphno.setEditable(false);
        Dmailid.setEditable(false);
        update.setVisible(false);
        this.dispose();
        new Signin().setVisible(true);
        try{
            ResultSet rs;   
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/forex","root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "delete from accountDetails where userName='"+Dname.getText()+"';";
            stmt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Account deleted", "Message",1);
               
        }
         
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        try{
            ResultSet rs;   
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/forex","root", "");
            Statement stmt = (Statement) con.createStatement();
            String query = "update accountDetails set userName='" +Duname.getText()+"',email='" +Dmailid.getText()+ "',phno='" + Dphno.getText()+"' where userName='"+UName+"';";
            stmt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Account details successfully updated", "Success message",1);
               
        }
         
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTextField Dmailid;
    private javax.swing.JTextField Dname;
    private javax.swing.JTextField Dphno;
    private javax.swing.JLabel Drole;
    private javax.swing.JTextField Duname;
    private javax.swing.JLabel LTitle;
    private javax.swing.JLabel Lmailid;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Lphno;
    private javax.swing.JLabel Lrole;
    private javax.swing.JLabel Luname;
    private javax.swing.JButton delete;
    private javax.swing.JButton display;
    private javax.swing.JButton logout;
    private javax.swing.JButton modify;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
